### ISSUE TITLE
Check ge does not seem work

### ISSUE THREAD

**Issue by ken-morel** [ken-morel/pyoload#12]
I tried
```python
@annotate
def ca(v=Checks(ge=3)) -> Checks(len=3):
    print(dkdkdjd)
    return 1, 2, 3


ca(5)
```

but is says
```
Traceback (most recent call last):
  File "C:\pyoload\src\del.py", line 24, in <module>
    ca(5)
  File "C:\pyoload\src\pyoload\__init__.py", line 339, in wrapper
    if not typeMatch(v, anno[k]):
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\pyoload\src\pyoload\__init__.py", line 225, in typeMatch
    spec(val)
  File "C:\pyoload\src\pyoload\__init__.py", line 146, in __call__
    Check.check(name, params, val)
  File "C:\pyoload\src\pyoload\__init__.py", line 73, in check
    check(val, params)
  File "C:\pyoload\src\pyoload\__init__.py", line 89, in len_check
    if not len(val) == params:
           ^^^^^^^^
TypeError: object of type 'int' has no len()
```

**Comment by ken-morel** [comment]
corrected the error, instead, will prefer using annotations than kwdefaults
